name: Test Jupyter Notebook 
on:
  push:
    branches:
      - main

  pull_request:
    branches: '**' # Any PR raised will trigger the workflow by 'opened, synchronize & reopened' events

jobs:
  build:
    name: Test Notebook with Python 3.9
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: classifai-image-retrieval
          python-version: 3.9

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install flake8_nb
          
      - name: Execute Flake8 to test
        shell: bash -l {0}
        run: |
          for i in **/**.ipynb; do 
            flake8_nb --select=E9,F63,F7 --notebook-cell-format '{nb_path}:code_cell#{code_cell_count}' "$i"
          done